fixed push events
Added a condition to check for pull events.

diff --git a/.github/workflows/build_test_notebooks.yml b/.github/workflows/build_test_notebooks.yml
--- a/.github/workflows/build_test_notebooks.yml
+++ b/.github/workflows/build_test_notebooks.yml
@@ -20,19 +20,28 @@ jobs:
           repository: StingraySoftware/stingray
           path: ./stingray
           submodules: recursive
-
-      - name: Get latest commit of the PR and Checkout PR version of notebooks
+      - name: Get latest commit of the PR or pushed commit and Checkout PR version of notebooks
         run: |
-          PR_SHA=$(curl -s 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}' | jq -r .head.sha)
-          if [ "$PR_SHA" == "null" ]; then
-            echo "::error::Failed to get PR SHA"
-            exit 1
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            echo "PR event detected. Fetching PR SHA..."
+            PR_SHA=$(curl -s 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}' | jq -r .head.sha)
+            if [ "$PR_SHA" == "null" ]; then
+              echo "::error::Failed to get PR SHA"
+              exit 1
+            fi
+            echo "commit=$PR_SHA" >> $GITHUB_ENV
+            cd ./stingray/docs/notebooks # Change to the submodule directory
+            pwd
+            git fetch origin $PR_SHA:pr_temp
+            git checkout pr_temp
+          else
+            echo "Push event detected. Using pushed commit SHA..."
+            echo "commit=${{ github.sha }}" >> $GITHUB_ENV
+            cd ./stingray/docs/notebooks # Change to the submodule directory
+            pwd
+            git fetch origin ${{ github.sha }}:pr_temp
+            git checkout pr_temp
           fi
-          echo "commit=$PR_SHA" >> $GITHUB_ENV
-          cd ./stingray/docs/notebooks # Change to the submodule directory
-          pwd
-          git fetch origin $PR_SHA:pr_temp
-          git checkout pr_temp
       - name: Verify submodule update
         run: |
           cd ./stingray/docs/notebooks
